import sys
sys.path.append('.')
from app.services.ocr_service import process_document

print('Testing Bravens Certificate:')
result = process_document('uploads/Bravens Inc. Certificate.pdf')
print(f'  Organization: {result["extracted_fields"]["organization"]}')
print(f'  Certificate #: {result["extracted_fields"]["certificate_number"]}')
print(f'  Issued: {result["extracted_fields"]["issued_date"]}')
print(f'  Expiry: {result["extracted_fields"]["expiry_date"]}')
print()
print('Testing Ampcus WBENC Certificate:')
result = process_document('uploads/Ampcus WBENC Certificate-Expires 102825.pdf')
print(f'  Organization: {result["extracted_fields"]["organization"]}')
print(f'  Certificate #: {result["extracted_fields"]["certificate_number"]}')
print(f'  Issued: {result["extracted_fields"]["issued_date"]}')
print(f'  Expiry: {result["extracted_fields"]["expiry_date"]}')
print()
print('Testing Ampcus NMSDC Certificate:')
result = process_document('uploads/Ampcus NMSDC Certificate-Expire 10312025.pdf')
print(f'  Organization: {result["extracted_fields"]["organization"]}')
print(f'  Certificate #: {result["extracted_fields"]["certificate_number"]}')
print(f'  Issued: {result["extracted_fields"]["issued_date"]}')
print(f'  Expiry: {result["extracted_fields"]["expiry_date"]}')
